name: Build and deploy GRASS conda packages

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build conda packages
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: latest
          environment-name: build
          create-args: conda-build
          cache-environment: true
          cache-downloads: true

      - name: Show micromamba environment
        shell: bash
        run: |
          micromamba info
          micromamba list

      - name: Build conda package
        shell: bash
        run: |
          micromamba run -n build conda config --set channel_priority strict
          micromamba run -n build conda config --add channels conda-forge
          micromamba run -n build conda build grass -c conda-forge --output-folder built

      - name: Upload conda packages
        uses: actions/upload-pages-artifact@v3
        with:
          path: built

  deploy:
    name: Deploy conda packages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy conda packages
        id: deployment
        uses: actions/deploy-pages@v4
