on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: latest
          environment-name: build
          create-args: >-
            python=${{ matrix.python }}
            conda-build
          cache-environment: true
          cache-downloads: true

      - shell: bash
        run: |
          micromamba info
          micromamba list

      - shell: bash
        run: |
          micromamba run -n build conda config --set channel_priority strict
          micromamba run -n build conda config --add channels conda-forge
          micromamba run -n build conda build grass -c conda-forge --output-folder built

      - uses: peaceiris/actions-gh-pages@v4
        with:
          if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: built
